# eva/utils/io_utils.py

import json
import glob
import os
from typing import List, Tuple, Any
from pathlib import Path

# ────────────────────────────────────────────────────────────────────────────
# Supports both JSON arrays and JSONL (one JSON object per line)
def load_json_any(fp: str | Path) -> Any:
    p = Path(fp)
    txt = p.read_text(encoding="utf-8")
    # Try parsing as a whole JSON array / object first
    try:
        return json.loads(txt)
    except json.JSONDecodeError:
        pass
    # Fall back to JSONL: parse line by line, skip blank lines
    items: List[Any] = []
    for ln in txt.splitlines():
        s = ln.strip()
        if not s:
            continue
        items.append(json.loads(s))
    return items
# ────────────────────────────────────────────────────────────────────────────

def build_ordered_corpus(corpus_dir: str, out_fp: str) -> List[str]:
    """
    1) Iterate all .json files sorted by filename.
    2) Within each file, extend the corpus in JSON array order.
    3) Write a deterministically ordered corpus.json list to out_fp.
    """
    files = sorted(glob.glob(os.path.join(corpus_dir, "*.json")))
    corpus: List[str] = []
    for fp in files:
        arr = load_json_any(fp)  # handles both JSON and JSONL
        # Accept string arrays or object arrays
        if isinstance(arr, list):
            for x in arr:
                if isinstance(x, str):
                    txt = x.strip()
                else:
                    txt = (str(x) if x is not None else "").strip()
                if txt:
                    corpus.append(txt)
        else:
            # Fallback: single object, convert to string
            s = (str(arr) if arr is not None else "").strip()
            if s:
                corpus.append(s)
    # Write the deterministically ordered corpus list
    Path(out_fp).parent.mkdir(parents=True, exist_ok=True)
    Path(out_fp).write_text(json.dumps(corpus, ensure_ascii=False), encoding="utf-8")
    print(f"✓ built ordered corpus: {out_fp} ({len(corpus):,d} passages)")
    return corpus

def load_ordered_corpus(corpus_json: str) -> List[str]:
    """
    Load from a JSON file generated by build_ordered_corpus.
    Guarantees reproducible list ordering.
    """
    return json.loads(Path(corpus_json).read_text(encoding="utf-8"))

def load_test_file(path: str):
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    queries = [item["user_query"].strip() for item in data]
    return data, queries

# ────────────────────────────────────────────────────────────────────────────
# Build TREC-COVID ordered corpus + aligned id list
def build_trec_covid_corpus(
    trec_corpus_fp: str | Path,
    out_corpus_fp: str | Path,
    out_ids_fp: str | Path,
    *,
    join_with: str = "\n",
) -> Tuple[List[str], List[str]]:
    trec_corpus_fp = Path(trec_corpus_fp)
    out_corpus_fp  = Path(out_corpus_fp)
    out_ids_fp     = Path(out_ids_fp)

    arr = load_json_any(trec_corpus_fp)  # handles both JSON and JSONL
    if not isinstance(arr, list):
        raise RuntimeError("trec_covid_corpus.json must be an object array or JSONL")

    texts: List[str] = []
    ids:   List[str] = []
    for it in arr:
        if not isinstance(it, dict):
            continue
        did   = str(it.get("_id", "")).strip()
        title = (it.get("title") or "").strip()
        text  = (it.get("text")  or "").strip()
        combined = f"{title}{join_with}{text}" if title else text
        combined = combined.strip()
        if combined:
            texts.append(combined)
            ids.append(did if did else "")
    out_corpus_fp.parent.mkdir(parents=True, exist_ok=True)
    out_ids_fp.parent.mkdir(parents=True, exist_ok=True)

    out_corpus_fp.write_text(json.dumps(texts, ensure_ascii=False), encoding="utf-8")
    out_ids_fp.write_text(json.dumps(ids,   ensure_ascii=False),   encoding="utf-8")
    print(f"✓ built trec ordered corpus: {out_corpus_fp} ({len(texts):,d}) + ids ({len(ids):,d})")
    return texts, ids

# ────────────────────────────────────────────────────────────────────────────
# Build Climate-FEVER ordered corpus + aligned id list
# Input: corpus.jsonl, each line: {"_id":"...", "title":"...", "text":"..."}
# Output:
#   ordered_corpus_climate.json
#   ordered_corpus_climate_ids.json  (aligned with above)
def build_climate_fever_corpus(
    src_corpus_fp: str | Path,
    out_corpus_fp: str | Path,
    out_ids_fp: str | Path,
    *,
    join_with: str = "\n",
) -> Tuple[List[str], List[str]]:
    src_corpus_fp = Path(src_corpus_fp)
    out_corpus_fp = Path(out_corpus_fp)
    out_ids_fp    = Path(out_ids_fp)

    arr = load_json_any(src_corpus_fp)  # JSONL/JSON compatible
    if not isinstance(arr, list):
        raise RuntimeError("climate_fever corpus.jsonl must be an object array or JSONL")

    texts: List[str] = []
    ids:   List[str] = []
    for it in arr:
        if not isinstance(it, dict):
            continue
        did   = str(it.get("_id", "")).strip()
        title = (it.get("title") or "").strip()
        text  = (it.get("text")  or "").strip()  # some entries have title only, no text
        combined = f"{title}{join_with}{text}" if title and text else (title or text)
        combined = (combined or "").strip()
        if combined:
            texts.append(combined)
            ids.append(did if did else "")
    out_corpus_fp.parent.mkdir(parents=True, exist_ok=True)
    out_ids_fp.parent.mkdir(parents=True, exist_ok=True)

    out_corpus_fp.write_text(json.dumps(texts, ensure_ascii=False), encoding="utf-8")
    out_ids_fp.write_text(json.dumps(ids,   ensure_ascii=False),   encoding="utf-8")
    print(f"✓ built climate ordered corpus: {out_corpus_fp} ({len(texts):,d}) + ids ({len(ids):,d})")
    return texts, ids

# ────────────────────────────────────────────────────────────────────────────
# Build BIOSSES ordered corpus + aligned id list
# Input: merged.jsonl, each line: {"id":"...","document_id":"...","text_1":"...","text_2":"...","label":"4.0"}
# Corpus is built from text_2; ids are taken from document_id (aligned with label_pool doc_ids)
def build_biosses_corpus(
    src_fp: str | Path,
    out_corpus_fp: str | Path,
    out_ids_fp: str | Path,
) -> Tuple[List[str], List[str]]:
    src_fp = Path(src_fp)
    out_corpus_fp = Path(out_corpus_fp)
    out_ids_fp    = Path(out_ids_fp)

    arr = load_json_any(src_fp)
    if not isinstance(arr, list):
        raise RuntimeError("biosses merged.jsonl must be an object array or JSONL")

    texts: List[str] = []
    ids:   List[str] = []
    for it in arr:
        if not isinstance(it, dict):
            continue
        did   = str(it.get("document_id", "")).strip()
        text2 = (it.get("text_2") or "").strip()
        if text2:
            texts.append(text2)
            ids.append(did if did else "")
    out_corpus_fp.parent.mkdir(parents=True, exist_ok=True)
    out_ids_fp.parent.mkdir(parents=True, exist_ok=True)

    out_corpus_fp.write_text(json.dumps(texts, ensure_ascii=False), encoding="utf-8")
    out_ids_fp.write_text(json.dumps(ids,   ensure_ascii=False),   encoding="utf-8")
    print(f"✓ built biosses ordered corpus: {out_corpus_fp} ({len(texts):,d}) + ids ({len(ids):,d})")
    return texts, ids
